server:
  port: 8761

spring:
  application:
    name: LOCALHOSTVN
  security:
    user:
      name: admin
      password: pwd

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  instance:
    hostname: localhost-vn
    appname: LOCALHOSTVN
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone:  http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
